### ISSUE TITLE
AM2315 installation on Raspberry Pi 2B

### ISSUE THREAD

**Issue by pvgennip** [vyykn/AM2315#1]
I would love to use the AM2315 on the newest Raspberry Pi 2B, but get these errors at installation.
Could you please take a look and tell me if you could help me out?

> am2315@1.0.3 install /home/pi/node_modules/am2315
> node-gyp rebuild

make: Entering directory '/home/pi/node_modules/am2315/build'
  CC(target) Release/obj.target/AM2315/src/bcm2835.o
  CXX(target) Release/obj.target/AM2315/AM2315.o
../AM2315.cpp:15:28: error: ‘Arguments’ does not name a type
../AM2315.cpp:15:39: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../AM2315.cpp:16:17: error: variable or field ‘AM2315Work’ declared void
../AM2315.cpp:16:17: error: ‘uv_work_t’ was not declared in this scope
../AM2315.cpp:16:28: error: ‘req’ was not declared in this scope
../AM2315.cpp:17:18: error: variable or field ‘AM2315After’ declared void
../AM2315.cpp:17:18: error: ‘uv_work_t’ was not declared in this scope
../AM2315.cpp:17:29: error: ‘req’ was not declared in this scope
../AM2315.cpp:49:28: error: ‘Arguments’ does not name a type
../AM2315.cpp:49:39: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h: In function ‘v8::Handlev8::Value AM2315(const int&)’:
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../AM2315.cpp:50:17: error: within this context
../AM2315.cpp:52:16: error: invalid types ‘const int[int]’ for array subscript
../AM2315.cpp:54:13: error: ‘New’ is not a member of ‘v8::String’
../AM2315.cpp:54:71: error: ‘ThrowException’ was not declared in this scope
../AM2315.cpp:57:60: error: invalid types ‘const int[int]’ for array subscript
../AM2315.cpp:64:57: error: no matching function for call to ‘v8::Persistentv8::Function::New(v8::Localv8::Function&)’
../AM2315.cpp:64:57: note: candidate is:
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:5798:4: note: static T\* v8::PersistentBase<T>::New(v8::Isolate_, T_) [with T = v8::Function]
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:5798:4: note:   candidate expects 2 arguments, 1 provided
../AM2315.cpp:67:5: error: ‘uv_work_t’ was not declared in this scope
../AM2315.cpp:67:16: error: ‘req’ was not declared in this scope
../AM2315.cpp:67:26: error: expected type-specifier before ‘uv_work_t’
../AM2315.cpp:67:26: error: expected ‘;’ before ‘uv_work_t’
../AM2315.cpp:83:48: error: ‘uv_default_loop’ was not declared in this scope
../AM2315.cpp:83:56: error: ‘AM2315Work’ was not declared in this scope
../AM2315.cpp:84:33: error: ‘uv_after_work_cb’ was not declared in this scope
../AM2315.cpp:84:61: error: ‘uv_queue_work’ was not declared in this scope
../AM2315.cpp:87:22: error: too few arguments to function ‘v8::Handlev8::Primitive v8::Undefined(v8::Isolate_)’
/home/pi/.node-gyp/0.12.6/deps/v8/include/v8.h:305:28: note: declared here
../AM2315.cpp: At global scope:
../AM2315.cpp:95:17: error: variable or field ‘AM2315Work’ declared void
../AM2315.cpp:95:17: error: ‘uv_work_t’ was not declared in this scope
../AM2315.cpp:95:28: error: ‘req’ was not declared in this scope
../AM2315.cpp: In function ‘v8::Handlev8::Value AM2315(const int&)’:
../AM2315.cpp:88:1: warning: control reaches end of non-void function [-Wreturn-type]
AM2315.target.mk:93: recipe for target 'Release/obj.target/AM2315/AM2315.o' failed
make: *_\* [Release/obj.target/AM2315/AM2315.o] Error 1
make: Leaving directory '/home/pi/node_modules/am2315/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.6-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/am2315
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 4.1.6-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "am2315"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! am2315@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the am2315@1.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the am2315 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls am2315
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by pvgennip** [comment]
I finally worked it out :-)

**Comment by 14yannick** [comment]
can you maybe share your solution thx

**Comment by pvgennip** [comment]
Sorry, I can't find the solution that I used anymore. But I decided that, since I had to read out more sensors, that where not available as Node packages, it was better for me to use Python scripts (https://github.com/roder/aosong) to read the sensor values and then read them from Node via a simple Bash script that echoes the values on demand.

**Comment by 14yannick** [comment]
Thanks for the advice. in the meantime I found this library https://github.com/vyykn/AM2315 . who works for me.
